import * as THREE from 'https://cdn.jsdelivr.net/npm/three@0.183.2/build/three.module.js'
window.THREE=THREE
const VIDEO_URL='./assets/diocletian-paul-lipsync.mp4'
const GARDEN_START=5.75
let video,figure,shadow,xrCamera,statusTimer,anchored=false
const $=id=>document.getElementById(id)
function setStatus(s,ms=0){const e=$('status'),c=document.querySelector('.status-card');e.textContent=s;c.style.display='block';if(statusTimer)clearTimeout(statusTimer);if(ms)statusTimer=setTimeout(()=>c.style.display='none',ms)}
function makeVideo(){const v=document.createElement('video');v.src=VIDEO_URL;v.loop=false;v.muted=true;v.playsInline=true;v.setAttribute('playsinline','');v.preload='auto';v.crossOrigin='anonymous';return v}
function softShadow(){const c=document.createElement('canvas');c.width=256;c.height=128;const x=c.getContext('2d'),g=x.createRadialGradient(128,64,8,128,64,120);g.addColorStop(0,'rgba(0,0,0,.30)');g.addColorStop(.5,'rgba(0,0,0,.12)');g.addColorStop(1,'rgba(0,0,0,0)');x.fillStyle=g;x.fillRect(0,0,256,128);return new THREE.CanvasTexture(c)}
function vignetteMaterial(map){return new THREE.ShaderMaterial({uniforms:{map:{value:map}},vertexShader:`varying vec2 vUv;void main(){vUv=uv;gl_Position=projectionMatrix*modelViewMatrix*vec4(position,1.);}`,fragmentShader:`uniform sampler2D map;varying vec2 vUv;float ellipse(vec2 p,vec2 c,vec2 r,float f){float d=length((p-c)/r);return 1.-smoothstep(1.-f,1.,d);}void main(){vec4 rgb=texture2D(map,vUv);float head=ellipse(vUv,vec2(.505,.735),vec2(.080,.135),.10);float torso=ellipse(vUv,vec2(.515,.525),vec2(.155,.235),.10);float armL=ellipse(vUv,vec2(.430,.405),vec2(.105,.205),.10);float armR=ellipse(vUv,vec2(.535,.385),vec2(.105,.205),.10);float hands=ellipse(vUv,vec2(.455,.245),vec2(.135,.115),.12);float soil=ellipse(vUv,vec2(.455,.125),vec2(.185,.095),.13);float plant=ellipse(vUv,vec2(.455,.245),vec2(.075,.135),.10);float a=max(max(max(head,torso),max(armL,armR)),max(max(hands,soil),plant));if(a<.015)discard;gl_FragColor=vec4(rgb.rgb,a);}`,transparent:true,side:THREE.DoubleSide,depthWrite:false,toneMapped:false})}
async function play(){if(!video)return; if(video.currentTime<GARDEN_START||video.currentTime>15.8)video.currentTime=GARDEN_START;await video.play()}
function build(scene){video=makeVideo();const tex=new THREE.VideoTexture(video);tex.colorSpace=THREE.SRGBColorSpace;tex.minFilter=THREE.LinearFilter;tex.magFilter=THREE.LinearFilter;tex.generateMipmaps=false;const h=2.15;figure=new THREE.Mesh(new THREE.PlaneGeometry(3.82,h),vignetteMaterial(tex));figure.position.set(0,h/2,-2.2);figure.renderOrder=2;scene.add(figure);shadow=new THREE.Mesh(new THREE.PlaneGeometry(1.45,.62),new THREE.MeshBasicMaterial({map:softShadow(),transparent:true,depthWrite:false,toneMapped:false}));shadow.rotation.x=-Math.PI/2;shadow.position.set(-.08,.012,-2.18);scene.add(shadow);video.addEventListener('loadedmetadata',()=>{video.currentTime=GARDEN_START;setStatus('Pomakni se oko prizora. Ovo je PoC izdvajanja vrtnog prizora.',5200);play().then(()=>{$('video-toggle').textContent='Pauziraj prizor'}).catch(()=>setStatus('Dodirni “Pokreni prizor”.',4200))});video.addEventListener('timeupdate',()=>{if(video.currentTime>=15.82){video.currentTime=GARDEN_START;if(!video.paused)video.play().catch(()=>{})}});video.addEventListener('error',()=>setStatus('Video se nije učitao. Osvježi stranicu i pokušaj ponovno.'))}
const mod=()=>({name:'diocletian-garden-spatial-poc',onStart:({canvas})=>{const {scene,camera}=XR8.Threejs.xrScene();xrCamera=camera;build(scene);camera.position.set(0,1.6,2.5);XR8.XrController.updateCameraProjectionMatrix({origin:camera.position,facing:camera.quaternion});canvas.addEventListener('touchmove',e=>e.preventDefault(),{passive:false});setStatus('Uspostavljam prostorni prikaz…')},onUpdate:()=>{if(!figure||!xrCamera||anchored)return;const dx=xrCamera.position.x-figure.position.x,dz=xrCamera.position.z-figure.position.z;figure.rotation.y=Math.atan2(dx,dz)}})
function start(){XR8.addCameraPipelineModules([XR8.GlTextureRenderer.pipelineModule(),XR8.Threejs.pipelineModule(),XR8.XrController.pipelineModule(),LandingPage.pipelineModule(),XRExtras.FullWindowCanvas.pipelineModule(),XRExtras.Loading.pipelineModule(),XRExtras.RuntimeError.pipelineModule(),mod()]);XR8.run({canvas:$('camerafeed')});$('anchor').onclick=()=>{if(!figure)return;anchored=!anchored;$('anchor').textContent=anchored?'Otključaj sidro':'Usidri u prostoru';$('anchor').setAttribute('aria-pressed',String(anchored));setStatus(anchored?'Prizor je usidren. Sad se pomakni oko njega.':'Sidro je otključano.',2600)};$('recenter').onclick=()=>{anchored=false;XR8.XrController.recenter();$('anchor').textContent='Usidri u prostoru';$('anchor').setAttribute('aria-pressed','false');setStatus('Prizor je ponovno postavljen.',2200)};$('video-toggle').onclick=async()=>{try{if(video?.paused){await play();$('video-toggle').textContent='Pauziraj prizor'}else{video.pause();$('video-toggle').textContent='Pokreni prizor'}}catch{setStatus('Preglednik je blokirao reprodukciju. Dodirni ponovno.')}};$('sound-toggle').onclick=()=>{if(!video)return;video.muted=!video.muted;const on=!video.muted;$('sound-toggle').textContent=on?'Isključi zvuk':'Uključi zvuk';$('sound-toggle').setAttribute('aria-pressed',String(on))}}
window.XR8?start():window.addEventListener('xrloaded',start)
