import * as THREE from 'https://cdn.jsdelivr.net/npm/three@0.183.2/build/three.module.js'
window.THREE=THREE
const PACKED_URL='./assets/diocletian-packed-alpha-plant-local-h264.mp4?v=20260923-local'
const GARDEN_START=5.75
let video,voice,voiceEnabled=false,figure,shadow,xrCamera,statusTimer,anchored=true
const $=id=>document.getElementById(id)
function setStatus(s,ms=0){const e=$('status'),c=document.querySelector('.status-card');e.textContent=s;c.style.display='block';if(statusTimer)clearTimeout(statusTimer);if(ms)statusTimer=setTimeout(()=>c.style.display='none',ms)}
function makeVideo(src=PACKED_URL){const v=document.createElement('video');v.src=src;v.loop=false;v.muted=true;v.playsInline=true;v.setAttribute('playsinline','');v.preload='auto';v.crossOrigin='anonymous';return v}
function softShadow(){const c=document.createElement('canvas');c.width=256;c.height=128;const x=c.getContext('2d'),g=x.createRadialGradient(128,64,8,128,64,120);g.addColorStop(0,'rgba(0,0,0,.30)');g.addColorStop(.5,'rgba(0,0,0,.12)');g.addColorStop(1,'rgba(0,0,0,0)');x.fillStyle=g;x.fillRect(0,0,256,128);return new THREE.CanvasTexture(c)}
function packedAlphaMaterial(map){return new THREE.ShaderMaterial({uniforms:{packedMap:{value:map}},vertexShader:`varying vec2 vUv;void main(){vUv=uv;gl_Position=projectionMatrix*modelViewMatrix*vec4(position,1.);}`,fragmentShader:`uniform sampler2D packedMap;varying vec2 vUv;void main(){vec2 rgbUv=vec2(vUv.x*.5,vUv.y);vec2 maskUv=vec2(.5+vUv.x*.5,vUv.y);vec4 rgb=texture2D(packedMap,rgbUv);float m=texture2D(packedMap,maskUv).r;float a=smoothstep(.045,1.,m*1.22);if(a<.01)discard;gl_FragColor=vec4(rgb.rgb,a);}`,transparent:true,side:THREE.DoubleSide,depthWrite:false,toneMapped:false})}
async function play(){if(!video)return;const t=(video.currentTime<GARDEN_START||video.currentTime>15.8)?GARDEN_START:video.currentTime;video.currentTime=t;const playing=video.play();if(voiceEnabled){voice.currentTime=t;void voice.play().catch(()=>setStatus('Dodirni “Uključi glas” za govor.',4200))}await playing}
function build(scene){video=makeVideo(PACKED_URL);voice=new Audio('./assets/diocletian-voice.m4a?v=20260923-audio-only');voice.preload='auto';voice.addEventListener('error',()=>setStatus('Govor se nije učitao.',5000));video.addEventListener('timeupdate',()=>{if(voiceEnabled&&Math.abs(voice.currentTime-video.currentTime)>.35)voice.currentTime=video.currentTime});video.addEventListener('pause',()=>voice.pause());video.addEventListener('playing',()=>{if(voiceEnabled&&voice.paused){voice.currentTime=video.currentTime;void voice.play().catch(()=>setStatus('Dodirni “Uključi glas” za govor.',5000))}});const tex=new THREE.VideoTexture(video);tex.colorSpace=THREE.SRGBColorSpace;tex.minFilter=THREE.LinearFilter;tex.magFilter=THREE.LinearFilter;tex.generateMipmaps=false;const h=3.25;figure=new THREE.Mesh(new THREE.PlaneGeometry(2.89,h),packedAlphaMaterial(tex));figure.position.set(0,h/2-.78,-2.2);figure.renderOrder=2;scene.add(figure);shadow=new THREE.Mesh(new THREE.PlaneGeometry(1.22,.46),new THREE.MeshBasicMaterial({map:softShadow(),transparent:true,depthWrite:false,toneMapped:false}));shadow.rotation.x=-Math.PI/2;shadow.position.set(-.08,.008,-2.18);scene.add(shadow);video.addEventListener('loadedmetadata',()=>{video.currentTime=GARDEN_START;setStatus('Pomakni se oko prizora. Ovo je PoC izdvajanja vrtnog prizora.',5200);play().then(()=>{$('video-toggle').textContent='Pauziraj prizor'}).catch(()=>setStatus('Dodirni “Pokreni prizor”.',4200))});video.addEventListener('timeupdate',()=>{if(video.currentTime>=15.82){video.currentTime=GARDEN_START;if(!video.paused)video.play().catch(()=>{})}});video.addEventListener('error',()=>setStatus('Video se nije učitao. Osvježi stranicu i pokušaj ponovno.'))}
const mod=()=>({name:'diocletian-garden-spatial-poc',onStart:({canvas})=>{const {scene,camera}=XR8.Threejs.xrScene();xrCamera=camera;build(scene);camera.position.set(0,1.6,2.5);XR8.XrController.updateCameraProjectionMatrix({origin:camera.position,facing:camera.quaternion});canvas.addEventListener('touchmove',e=>e.preventDefault(),{passive:false});setStatus('Uspostavljam prostorni prikaz…')},onUpdate:()=>{}})
function start(){XR8.addCameraPipelineModules([XR8.GlTextureRenderer.pipelineModule(),XR8.Threejs.pipelineModule(),XR8.XrController.pipelineModule(),LandingPage.pipelineModule(),XRExtras.FullWindowCanvas.pipelineModule(),XRExtras.Loading.pipelineModule(),XRExtras.RuntimeError.pipelineModule(),mod()]);XR8.run({canvas:$('camerafeed')});$('recenter').onclick=()=>{XR8.XrController.recenter();setStatus('Prostorno sidro je ponovno postavljeno.',2200)};$('video-toggle').onclick=async()=>{try{if(video?.paused){await play();$('video-toggle').textContent='Pauziraj prizor'}else{video.pause();$('video-toggle').textContent='Pokreni prizor'}}catch{setStatus('Preglednik je blokirao reprodukciju. Dodirni ponovno.')}};$('sound-toggle').onclick=()=>{window.removeEventListener('pointerdown',enableSoundOnTouch,true);if(voiceEnabled){voiceEnabled=false;voice?.pause();$('sound-toggle').textContent='Uključi glas';$('sound-toggle').setAttribute('aria-pressed','false')}else void startVoice()}}
// Play speech independently of the muted video texture, after a mobile user gesture.
async function startVoice(){
  if(!video||!voice)return;
  try{voice.currentTime=video.currentTime;await voice.play();voiceEnabled=true;$('sound-toggle').textContent='Isključi glas';$('sound-toggle').setAttribute('aria-pressed','true')}
  catch{setStatus('Govor se nije pokrenuo. Dodirni “Uključi glas”.',5000)}
}
function enableSoundOnTouch(event){
  if(!video||event.target.closest?.('#sound-toggle'))return;
  window.removeEventListener('pointerdown',enableSoundOnTouch,true);
  void startVoice();
}
window.addEventListener('pointerdown',enableSoundOnTouch,true);
window.XR8?start():window.addEventListener('xrloaded',start)
